project:
  type: website
  output-dir: docs

website:
  title: "Kate Roetcisoender's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: data_problem.qmd
        text: "Example Data Problem"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

