---
title: "About"
---

### Kate Roetcisoender

I am an undergraduate student at Cal State University, Monterey Bay majoring in marine science and minoring in statistics, and graduating in Spring 2025. I have worked in Dr. James Lindholm's Image Analysis and Fish Ecology Lab for almost three years and have extensive experience in the field, analyzing video, and data processing. <br> <br> I grew up in the Mojave desert with few visits to the ocean, but still managed to find my passion for marine science. I have since moved to Monterey, California, where I get to see the ocean everyday, as well as work towards long-term monitoring solutions to understand the health of fish communities worldwide. I have been working on an independent project under Dr. James Lindholm analyzing the relative merits of various forms of video data collection, with the hopes of submitting for publication shortly after graduation. Additionally, I have been assisting in the virtual reality (VR) diving program, which has allowed me to participate in bringing underwater footage to high school classrooms to teach about marine science, marine protected areas, and research diving. Through all of these experiences, I have fallen further in love with marine science and the ocean, and plan to pursue making a difference for the rest of my life.
